language: android
jdk: oraclejdk7
android:
  components:
  - platform-tools
  - tools
  - extra
  - add-on
  - android-20
  - build-tools-20.0.0
branches:
  only:
  - master
  - release
before_script:
- echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
- emulator -avd test -no-skin -no-audio -no-window &
- adb wait-for-device
- adb shell input keyevent 82 &
before_deploy:
- DATE=$(date +"%Y%m%d%H%M%S")
- mkdir ./app/build/outputs/apk/$DATE
- mv ./app/build/outputs/apk/*.apk ./app/build/outputs/apk/$DATE
deploy:
  provider: s3
  access_key_id: AKIAIBBGKA3NPYIBCAIA
  secret_access_key:
    secure: IDpKjBkL7j5tXEHwjQwpmiMLEqz005MwOcSpHdlqka9zHI2RlLy1n5cfbsWcR6eBv5A6aYvliJ4Uyz5q3+dbKzzPVmas3F3a8OcX3tSKUn1ik8k6fb7myAB90tSi19RvcJZg7uXkIxMMaV916k+bFUn3oIPIZUIvK27gSgnV0Bw=
  bucket: seq-android-binaries
  upload-dir: qa
  local-dir: app/build/outputs/apk
  on:
    branch: master
  region: us-west-2
  skip_cleanup: true
