language: android
jdk: oraclejdk7
android:
  components:
  - platform-tools
  - tools
  - extra
  - add-on
  - android-20
  - build-tools-20.0.0
#branches:
#  only:
#  - master
#  - release
before_script:
  - sudo apt-get install ruby1.9.1
  - sudo apt-get install ruby1.9.1-dev
  - sudo gem install rspec
  - sudo gem install calabash-android
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &
before_deploy:
  - DATE=$(date +"%Y%m%d%H%M%S")
  - mkdir ./app/build/outputs/apk/$DATE
  - mv ./app/build/outputs/apk/*.apk ./app/build/outputs/apk/$DATE
deploy:
  provider: s3
  access_key_id: AKIAI4VIICLJVGBXUWKQ
  secret_access_key:
    secure: ZjfG2wqHx4EgoMZ4cR116tI7KjRxQA9XaTnhylo4jw9bUtRXzZGGyAa0k7sYODO8mGh9jx6pXiXEzfTX9JFKodeI8cMW7WgIsLdJPkPSDR4ouep0njk7Kf/ln1OBcIa499uNZtkOizVXvsFNXRmT8Lmw9vHE9Qi7qalyG35jzbM=
  bucket: seq-android-binaries
  upload-dir: qa/cliffy-android-geoquiz
  local-dir: app/build/outputs/apk
  on:
    branch: master
  region: us-west-2
  skip_cleanup: true
