language: android
jdk: oraclejdk7
android:
    components:
        - platform-tools
        - tools
        - extra
        - add-on
        - android-20
        - build-tools-20.0.0

branches:
  only:
  - master
  - release

before_script:
  # Create and start emulator
  #- echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  #- emulator -avd test -no-skin -no-audio -no-window &
  #- adb wait-for-device
  #- adb shell input keyevent 82 &
